name: canoe

services:
  dev:
    image: canoe
    build:
      context: .
      dockerfile: docker/Dockerfile
      ssh:
        - default
      args:
        UBUNTU_VER: "22.04"
        CUDA_VER: "12.9.1"
        NVHPC_VER: "26.3"
        TORCH_VER: "2.10.0"
        PYDISORT_VER: "v1.7.3"
        PYHARP_VER: "v2.4.6"
        KINTERA_VER: "v2.3.6"
        SNAPY_VER: "v2.6.2"
        PYMINICHEM_VER: "v0.3.4"
    environment:
      - USERNAME=${USER}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
    volumes:
      - ..:/work
      - ${GITCONFIG}:/etc/gitconfig
      - ${GITCREDENTIALS}:/etc/git-credentials
    working_dir: /work
    tty: true
    stdin_open: true
    ports:
      - "8888:8888"
