name: canoe

services:
  dev:
    image: canoe
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UBUNTU_VER: "22.04"
        CUDA_VER: "12.9.1"
        PYHARP_VER: "v1.9.4"
        KINTERA_VER: "v1.3.2"
        SNAPY_VER: "v1.3.5"
    environment:
      - USERNAME=${USER}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
    volumes:
      - ..:/work
      - ${GITCONFIG}:/etc/gitconfig
      - ${GITCREDENTIALS}:/etc/git-credentials
    working_dir: /work
    tty: true
    stdin_open: true
    ports:
      - "8888:8888"
